apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: horreum-build-image
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^((/build-image)|(/test-all))$"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/on-cel-expression: |-
      (
        ".tekton/build-image.yaml".pathChanged() ||
        "horreum-backend/**".pathChanged() ||
        "horreum-web/**".pathChanged() ||
        "horreum-api/**".pathChanged() ||
        "pom.xml".pathChanged()
      ) && (
        event == "push" && (
          source_branch.matches("^(main|master|alauda-deploy)$") ||
          target_branch.matches("^(main|master|alauda-deploy)$")
        )
      )
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: alauda
      - name: type
        value: tekton
      - name: kind
        value: pipeline
      - name: name
        value: clone-image-build-test-scan
      - name: version
        value: "0.2"

  params:
    - name: git-url
      value: "{{ repo_url }}"
    - name: git-revision
      value: "{{ source_branch }}"
    - name: git-commit
      value: "{{ revision }}"
    - name: pull-request-number
      value: "{{ pull_request_number }}"

    - name: image-repository
      value: build-harbor.alauda.cn/devops/horreum

    - name: tag-template
      value: ${Major}.${Minor}.${Patch}-g${ShortSha}

    - name: tags
      value:
        - "latest"
        - "{{ source_branch }}"

    - name: dockerfile-path
      value: .tekton/dockerfiles/horreum.Dockerfile

    - name: context
      value: "."

    - name: file-list-for-commit-sha
      value:
        - .tekton/build-image.yaml
        - .tekton/dockerfiles/horreum.Dockerfile
        - horreum-backend
        - horreum-web
        - horreum-api
        - pom.xml

    - name: prepare-tools-image
      value: "docker-mirrors.alauda.cn/library/maven:3.9-eclipse-temurin-17"

    - name: prepare-command
      value: |
        #!/bin/bash
        set -ex

        # 设置 HOME 目录
        export HOME=/root

        # 1. 安装父 POM
        mvn clean install -DskipTests -DskipITs -N

        # 2. 安装 API 模块
        mvn install -DskipTests -DskipITs -pl horreum-api

        # 3. 构建 backend (启用 Quinoa 打包前端，禁用 JIB 镜像构建)
        mvn package -DskipTests -DskipITs \
          -pl horreum-backend \
          -Dquarkus.package.jar.type=fast-jar \
          -Dquarkus.quinoa=true \
          -Dquarkus.container-image.build=false

        echo "Maven build completed"
        ls -la horreum-backend/target/quarkus-app/

    # 暂时忽略安全扫描
    - name: ignore-trivy-scan
      value: "true"

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 2Gi
    - name: dockerconfig
      secret:
        secretName: build-harbor.kauto.docfj
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: gitversion-config
      configMap:
        name: gitversion-config

  taskRunTemplate:
    podTemplate:
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: "OnRootMismatch"

  taskRunSpecs:
    - pipelineTaskName: prepare-build
      podTemplate:
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 0
          fsGroupChangePolicy: "OnRootMismatch"
      computeResources:
        limits:
          cpu: "4"
          memory: 8Gi
        requests:
          cpu: "2"
          memory: 4Gi
    - pipelineTaskName: build-image
      computeResources:
        limits:
          cpu: "4"
          memory: 4Gi
        requests:
          cpu: "2"
          memory: 2Gi
