apiVersion: v1
kind: Service
metadata:
  name: artemis-service
  namespace: horreum
  labels:
    app: artemis
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 8161
      targetPort: 8161
      name: console
  selector:
    app: artemis
