apiVersion: v1
kind: Service
metadata:
  name: horreum-service
  namespace: horreum
  labels:
    app: horreum
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http
  selector:
    app: horreum
